### ISSUE TITLE
Test datapackage library with all datapackages in /datasets organisation

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/testsuite-py#12]
This issue was originally in https://github.com/trickvi/datapackage/issues/63 by @femtotrader.

I'm not sure on how hard it'll be, but it might be useful to try loading all datapackages in /datasets as part of the test suite for datapackages library.

**Comment by roll** [comment]
It could be thing proposed by @danfowler - a badge with valid/invalid datapackage.

So backlogged for now here.

**Comment by roll** [comment]
It will be implemented as https://github.com/frictionlessdata/ideas/issues/198

https://github.com/frictionlessdata/ex-continuous-data-integration
