### ISSUE TITLE
Fix git source

### ISSUE THREAD

**Issue by roll** [frictionlessdata/testsuite-py#9]
Because of circular dependency between packages - https://github.com/frictionlessdata/tabulator-py/issues/51 - if in `requirements.git.txt` `tabulator` goes first we have `jsontableschema` from PyPi (not from Git as desired) and otherwise.

**Comment by pwalsh** [comment]
This is a common problem with Python packaging. Just make sure to require the one we actually need last, so it overrides previous installs.
